### ISSUE TITLE
Sorry, an error occurred while trying to access this service

### ISSUE THREAD

**Issue by anujdamania** [OfficeDev/microsoft-teams-apps-company-communicator#265]
We are receiving the message "Sorry, an error occurred while trying to access this service" on the Author application. We've confirmed App registration settings are all correct including application URI and API permissions. We've resynced and confirmed deployment of all components are correct in the Web Application.

We've double checked botid's and app names. We've also retried the deployment twice from scatch and still are recieving this same issue.

When looking in log analytics we are seeing error 401's on number of Get - API's

**Comment by layinka** [comment]
We are experiencing the same thing too.

**Comment by layinka** [comment]
Pls, is there any fix for this yet?

**Comment by franzbuenaventura** [comment]
Same Issue

**Comment by layinka** [comment]
@franzbuenaventura 
Pls what did you change and how did you deploy it on the same tenant?

**Comment by sergiorru** [comment]
Did you guy's are deploying on the same tenant or in different tenants?

In my case, when i deployed in different tenants (eg.: App is hosted on tenant A and the users are on the tenant B) is necessary specify the **AzureAd:TenantId** setting on the Bot WebApp, in this case, this will be the ID of the Tenant B (that hosts the users).

**Comment by franzbuenaventura** [comment]
> @franzbuenaventura
> Pls what did you change and how did you deploy it on the same tenant?

When I say deploy in the same tenant I mean the Azure Directory is the same tenant with the Teams I deployed too. 



> Did you guy's are deploying on the same tenant or in different tenants?
> 
> In my case, when i deployed in different tenants (eg.: App is hosted on tenant A and the users are on the tenant B) is necessary specify the **AzureAd:TenantId** setting on the Bot WebApp, in this case, this will be the ID of the Tenant B (that hosts the users).

I tried both, on the instruction you need to insert Tenant B on Configuration (Deployment part 2.6) but that didn't work. 
I got the issue I posted earlier #267

**Comment by anujdamania** [comment]
I had realised I hadn't updated tenant id as @sergiorru  mentioned in the initial deployment. Doing it after the fact in the web application didn't resolve the the issue even after doing a full code redeploy. What I had to do was start from scratch and make sure Azure AD Tenant ID was in the RMS template deploy code and is all working as expected.

**Comment by bungleweed** [comment]
Getting this issue in a single tenant deployment. 401 errors accessing api/draftnotifications and api/sentnotifications

**Comment by snailCorpse** [comment]
Hi All

I found that the Configuration settings deployed is different to the AzureAd:ApplicationIdURI that's is created. Check the url for the applicationURI. in the communicator configuration settings

**Comment by snailCorpse** [comment]
Hi All

I found that the Configuration settings deployed is different to the AzureAd:ApplicationIdURI that's is created. Check the url for the applicationURI. in the communicator configuration settings
